set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'tmux-plugins/tmux-sensible'
set-option -g @plugin 'tmux-plugins/tmux-resurrect'

set-option -g @resurrect-processes 'ssh journalctl dmesg'

run '~/.tmux/plugins/tpm/tpm'
